import { Link, useParams } from "react-router-dom";

// Demo invite-accept landing page. The inviteToken in the URL is generated by
// `inviteContractor()`; production wiring (real auth + invite tokens stored
// server-side) is out of scope per CLAUDE.md "Trust Boundary". Today's flow:
// the manager creates an invite via the Contractors page, copies the link,
// hands it to the applicator out-of-band; clicking it lands here and shows a
// friendly confirmation. The applicator record is ALREADY in IndexedDB at
// this point — the invite link is informational rather than gating.
export function InviteAcceptPage() {
  const { token } = useParams<{ token: string }>();

  return (
    <div
      style={{
        maxWidth: 600,
        margin: "48px auto",
        padding: 24,
        backgroundColor: "var(--color-surface)",
        border: "1px solid var(--color-border)",
        borderRadius: 8,
        boxShadow: "var(--shadow-card)",
      }}
      data-testid="invite-accept-page"
    >
      <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 12 }}>
        FieldLog invite
      </h1>
      <p style={{ fontSize: 14, color: "var(--color-text-secondary)", marginBottom: 16 }}>
        You've been invited to use FieldLog by a manager at the organization
        that sent you this link.
      </p>
      <div
        style={{
          fontSize: 12,
          color: "var(--color-text-secondary)",
          padding: "8px 12px",
          backgroundColor: "rgba(0,0,0,0.04)",
          borderRadius: 6,
          marginBottom: 24,
          fontFamily: "monospace",
        }}
      >
        Invite token: <strong data-testid="invite-token">{token}</strong>
      </div>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
        <Link to="/login" style={{ textDecoration: "none" }}>
          <button
            style={{
              height: 40,
              padding: "0 16px",
              backgroundColor: "var(--color-primary)",
              color: "#fff",
              border: "none",
              borderRadius: 6,
              fontSize: 14,
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Sign in to FieldLog
          </button>
        </Link>
        <Link to="/" style={{ textDecoration: "none" }}>
          <button
            style={{
              height: 40,
              padding: "0 16px",
              backgroundColor: "transparent",
              color: "var(--color-primary)",
              border: "1px solid var(--color-primary)",
              borderRadius: 6,
              fontSize: 14,
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Home
          </button>
        </Link>
      </div>
      <p
        style={{
          fontSize: 11,
          color: "var(--color-text-secondary)",
          marginTop: 24,
          fontStyle: "italic",
        }}
      >
        Demo build: this invite flow is UI scaffolding only. Real invite
        validation (token expiry, single-use redemption, server-side identity)
        lands when the backend is wired in. See CLAUDE.md "Trust Boundary".
      </p>
    </div>
  );
}
