import type { Product } from "../domain/types";

// Curated Missouri-relevant Restricted Use Products sourced from EPA's RUP
// Summary Report (research/regulatory/markdown_conversions/rups-rpt_table.csv).
// All entries are RUP by definition. Auto-generated by scripts/generateRupSeed.mjs;
// edit the script, not this file. Selection bucketed by active-ingredient
// family with a per-family cap so the demo product picker tells a coherent
// story (insecticide / herbicide / rodenticide / fumigant) and exercises every
// path in the compliance engine — RUP_UNCERTIFIED, indoor exemption,
// structural/termite exception, etc.

export const RUP_CATALOG_VERSION = "MO-DEMO-2026-05-21";

export type RupFamily =
  | "insecticide_corn"
  | "insecticide_pyrethroid"
  | "insecticide_carbamate"
  | "insecticide_op"
  | "insecticide_misc"
  | "herbicide_burndown"
  | "herbicide_corn_soy"
  | "herbicide_range"
  | "herbicide_glufosinate"
  | "rodenticide"
  | "fumigant"
  | "fungicide"
  | "wood_preservative";

type RupSeed = {
  epaRegistrationNumber: string;
  name: string;
  manufacturer: string;
  activeIngredient: string;
  family: RupFamily;
};

// Total curated entries: 211. Generated 2026-05-21.
const RUPS: RupSeed[] = [

  // ── Soil insecticide (corn rootworm) (14) ─────────────────────────────────
  { epaRegistrationNumber: "100-1075", name: "Force 3G Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "100-1253", name: "Force Cs Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "100-1361", name: "Force Sb", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "100-1610", name: "Force Evo", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "100-1615", name: "Force 10G HL Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "100-1625", name: "Force 6.5G Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-493", name: "Chlorethoxyfos 5G Granular", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Chlorethoxyfos", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-561", name: "Smartchoice 5G", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Bifenthrin, Chlorethoxyfos", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-576", name: "Amv1118 20G Granular Insect", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Chlorethoxyfos, Bifenthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-578", name: "Amv1118 10G Granular Insect", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Chlorethoxyfos, Bifenthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-579", name: "Amv1118 15G Granular Insect", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Chlorethoxyfos, Bifenthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "5481-587", name: "Smartchoice Liquid Insecticid", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Bifenthrin, Chlorethoxyfos", family: "insecticide_corn" },
  { epaRegistrationNumber: "83529-123", name: "Sharda Tefluthrin 3% Gr", manufacturer: "Sharda USA LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },
  { epaRegistrationNumber: "83529-199", name: "Sharda Tefluthrin 24.2% EC", manufacturer: "Sharda USA LLC", activeIngredient: "Tefluthrin", family: "insecticide_corn" },

  // ── Pyrethroid foliar insecticide (20) ─────────────────────────────────
  { epaRegistrationNumber: "100-1086", name: "Karate Ec-W Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1088", name: "Scimitar Gc Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1097", name: "Karate Insecticide With Zeon", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1112", name: "Warrior Insecticide With Zeo", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1276", name: "Endigo Zc", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Thiamethoxam, lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1295", name: "Warrior Ii With Zeon Technol", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1320", name: "Voliam Xpress Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin, Chlorantraniliprole", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1402", name: "Besiege Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Chlorantraniliprole, lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-1458", name: "Endigo ZCX", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Thiamethoxam, lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "100-998", name: "Karate 1EC", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "228-458", name: "Menace Gc 7.9% Flowable", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Bifenthrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "228-524", name: "Menace Gc 0.029% Plus Fertili", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Bifenthrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "228-526", name: "Kaiso 24WG Insecticide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "228-708", name: "Nufarm Lambda-Cyhalothrin", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "lambda-Cyhalothrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "228-717", name: "Kilter Insecticide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "lambda-Cyhalothrin, Imidacloprid", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "264-1011", name: "Decis 1.5EC Insecticide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Deltamethrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "264-1104", name: "Leverage 360 Insecticide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "beta-Cyfluthrin, Imidacloprid", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "264-1199", name: "Decis 100EC Insecticide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Deltamethrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "264-745", name: "Baythroid 2 Emulsifiable Pyre", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Cyfluthrin", family: "insecticide_pyrethroid" },
  { epaRegistrationNumber: "264-770", name: "Leverage 2.7 Suspension Emul", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Imidacloprid, Cyfluthrin", family: "insecticide_pyrethroid" },

  // ── Carbamate insecticide (20) ─────────────────────────────────
  { epaRegistrationNumber: "352-372", name: "Vydate L", manufacturer: "Corteva Agriscience, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "352-532", name: "Vydate C-Lv", manufacturer: "Corteva Agriscience, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "61842-52", name: "Lannate SP INSECTICIDE", manufacturer: "Tessenderlo Kerley, Inc.", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "61842-55", name: "Lannate Lv Insecticide", manufacturer: "Tessenderlo Kerley, Inc.", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "82557-2", name: "Methomyl 29SL Insecticide", manufacturer: "Sinon USA, Inc.", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "82557-3", name: "Methomyl 90Wsp", manufacturer: "Sinon USA, Inc.", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "83100-27", name: "Rotam Methomyl 29lv Insecti", manufacturer: "Albaugh, LLC", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "83100-28", name: "Rotam Methomyl 90SP Insecti", manufacturer: "Albaugh, LLC", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "83100-52", name: "Oxamyl 42% SL", manufacturer: "Albaugh, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "83100-53", name: "Oxamyl 24% SL", manufacturer: "Albaugh, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "87290-76", name: "Willowood Oxamyl C-LV", manufacturer: "Generic Crop Science, Lcc", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "87290-77", name: "Willowood Oxamyl L", manufacturer: "Generic Crop Science, Lcc", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "87895-1", name: "Meymik 15G", manufacturer: "Aglogic Chemical, LLC", activeIngredient: "Aldicarb", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "87895-4", name: "Aglogic 15gg", manufacturer: "Aglogic Chemical, LLC", activeIngredient: "Aldicarb", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "88058-6", name: "Oxamyl 42 Insecticide/Nemati", manufacturer: "Orion Ato, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "88058-8", name: "Oxamyl 24 Insecticide/Nemati", manufacturer: "Orion Ato, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "89167-91", name: "AX Methomyl 29LV Insecticide", manufacturer: "Axion Ag Products, LLC", activeIngredient: "Methomyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "89167-92", name: "Ax Oxamyl 42% Sl", manufacturer: "Axion Ag Products, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "89167-94", name: "Ax Oxamyl 24% Sl", manufacturer: "Axion Ag Products, LLC", activeIngredient: "Oxamyl", family: "insecticide_carbamate" },
  { epaRegistrationNumber: "CA770308", name: "Du Pont Lannate Sp Insecticid", manufacturer: "Tessenderlo Kerley, Inc.", activeIngredient: "Methomyl", family: "insecticide_carbamate" },

  // ── Organophosphate insecticide (20) ─────────────────────────────────
  { epaRegistrationNumber: "1015-68", name: "Max Kill Vapo-Cide", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-204", name: "Ddvp 4-E Emulsifiable Concen", manufacturer: "Amvac Chemical Corporation", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-205", name: "Ddvp 2-E Emulsifiable Concen", manufacturer: "Amvac Chemical Corporation", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-220", name: "Ddvp 5% Emulsifiable Concen", manufacturer: "Amvac Chemical Corporation", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-479", name: "Dibrom 8 Emulsive", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Naled", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-480", name: "Dibrom Concentrate", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Naled", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-481", name: "Trumpet Ec Insecticide", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Naled", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-482", name: "Fly Killer D", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Naled", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-526", name: "Thimet 10-G Soil And Systemic", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Phorate", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-527", name: "Thimet 15-G Soil And Systemic", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Phorate", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-530", name: "Thimet 20-G", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Phorate", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-545", name: "Counter 15G Systemic Insectic", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Terbufos", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-547", name: "Counter Cr", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Terbufos", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-553", name: "Amvac Small Pro-Strip", manufacturer: "Amvac Chemical Corporation", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-554", name: "Amvac Large Pro-Strip", manufacturer: "Amvac Chemical Corporation", activeIngredient: "DDVP", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-562", name: "Counter 20G", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Terbufos", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-9040", name: "Mocap 15% Granular Nematic", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Ethoprop", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-9041", name: "Mocap Ec Nematicide - Insecti", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Ethoprop", family: "insecticide_op" },
  { epaRegistrationNumber: "5481-9042", name: "Mocap 20% Granular Lock 'n", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Ethoprop", family: "insecticide_op" },
  { epaRegistrationNumber: "11556-162", name: "Ravap Ec Livestock, Poultry &", manufacturer: "Elanco US Inc.", activeIngredient: "Gardona (cis-isomer), DDVP", family: "insecticide_op" },

  // ── Other restricted insecticide (20) ─────────────────────────────────
  { epaRegistrationNumber: "100-1154", name: "Epi-Mek 0.15EC Miticide/Insect", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1204", name: "Avicta 500Fs", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1211", name: "Avicta 400Fs", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1321", name: "Avicta Duo", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Thiamethoxam, Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1350", name: "Agri-Flex Miticide/Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Thiamethoxam, Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1351", name: "Agri-Mek Sc Miticide/Insectici", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1353", name: "Avicta Duo 250", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Thiamethoxam, Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1405", name: "Avicta Complete Corn 250", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin, Thiamethoxam, Fludioxonil, Metalaxyl-M, Azoxystrobin, Thiabendazole", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1408", name: "EPI-MEK SC", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1439", name: "Epi-Mek SCL", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1440", name: "Solvigo Miticide/Insecticide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin, Thiamethoxam", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1457", name: "Avicta Complete Beans 500", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Metalaxyl-M, Fludioxonil, Thiamethoxam, Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1510", name: "Divanem 0.15EC", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1538", name: "Avicta Duo Cot202", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin, Thiamethoxam", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1549", name: "Quindigo", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Azoxystrobin, Propiconazole, lambda- Cyhalothrin, Thiamethoxam", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1592", name: "Minecto Pro", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin, Cyantraniliprole", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-1611", name: "Divanem", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "100-898", name: "Agri-Mek 0.15EC Miticide/Inse", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "228-658", name: "Nufarm Abamectin 0.15EC Ins", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Abamectin", family: "insecticide_misc" },
  { epaRegistrationNumber: "228-734", name: "Nup-13026 Abamectin 0.15Miti", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Abamectin", family: "insecticide_misc" },

  // ── Burndown / contact herbicide (20) ─────────────────────────────────
  { epaRegistrationNumber: "100-1652", name: "Gramoxone 3LB", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "5905-637", name: "Paraquat Concentrate", manufacturer: "Helena Agri-Enterprises, LLC, d/b/a Helena Chemical Comp", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "19713-617", name: "Drexel Quik-Quat", manufacturer: "Drexel Chemical Company", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "34704-1117", name: "Lpi 6620 Paraquat 3SL", manufacturer: "Loveland Products, Inc.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "74530-48", name: "Helmquat 3SL", manufacturer: "Helm Agro US, Inc.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "82542-26", name: "Dynaquat", manufacturer: "Source Dynamics, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "82542-3", name: "Paraquat Concentrate", manufacturer: "Source Dynamics, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "82557-1", name: "Paraquat Sl Herbicide", manufacturer: "Sinon USA, Inc.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "83529-27", name: "Paraquat Concentrate", manufacturer: "Sharda USA LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "85678-58", name: "Paraquat 43.2% SL", manufacturer: "Redeagle International LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "87290-35", name: "Willowood Paraquat Conce", manufacturer: "Generic Crop Science, Lcc", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "89167-24", name: "Ax Paraquat Concentrate", manufacturer: "Axion Ag Products, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "89168-25", name: "Liberty Paraquat Concentrat", manufacturer: "Liberty Crop Protection, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "89432-1", name: "Parazone 3SL Herbicide", manufacturer: "Nanjing Red Sun Biochemistry Co., Ltd.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "89432-2", name: "Parazone 2SL", manufacturer: "Nanjing Red Sun Biochemistry Co., Ltd.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "92647-12", name: "Tigris Paraquat", manufacturer: "Tigris, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "93809-4", name: "Axill Solutions Paraquat 3SL", manufacturer: "Axill Solutions, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "101458-2", name: "Crop Protect Direct Paraquat 3SL", manufacturer: "Jabco, LLC", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "AZ210101", name: "Helmquat 3SL", manufacturer: "Helm Agro US, Inc.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },
  { epaRegistrationNumber: "ID080009", name: "Paraquat Sl Herbicide", manufacturer: "Macdermid Agricultural Solutions, Inc.", activeIngredient: "Paraquat dichloride", family: "herbicide_burndown" },

  // ── Corn / soybean herbicide (20) ─────────────────────────────────
  { epaRegistrationNumber: "100-1161", name: "Expert Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine, Glyphosate, isopropylamine salt, S- Metolachlor", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-1359", name: "Callisto Xtra", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Mesotrione, Atrazine", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-1414", name: "Lexar Ez Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Mesotrione, Atrazine, S-Metolachlor", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-1442", name: "Lumax EZ Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "S-Metolachlor, Atrazine, Mesotrione", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-1466", name: "Acuron Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine, S-Metolachlor, Mesotrione, Bicyclopyrone", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-1668", name: "A22668", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine, Bicyclopyrone, S-Metolachlor, Mesotrione", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-497", name: "Aatrex 4L Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-585", name: "Aatrex Nine-O Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-817", name: "Bicep Ii Magnum Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine, S-Metolachlor", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "100-827", name: "Bicep Lite Ii Magnum Herbicide", manufacturer: "Syngenta Crop Protection, LLC", activeIngredient: "Atrazine, S-Metolachlor", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-1066", name: "Corvus Herbicide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Thiencarbazone-methyl, Isoxaflutole", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-1067", name: "Balance Flexx Herbicide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Isoxaflutole", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-1211", name: "USH0720", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Thiencarbazone-methyl, Flufenacet, Isoxaflutole", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-600", name: "Balance Pro Herbicide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Isoxaflutole", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-800", name: "Epic Df Herbicide", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Isoxaflutole, Flufenacet", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "264-852", name: "Flufenacet & Isoxaflutole Sc", manufacturer: "Bayer Cropscience Lp", activeIngredient: "Isoxaflutole, Flufenacet", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "279-9670", name: "ATZ-PYR-FM Herbicide", manufacturer: "Fmc Corporation", activeIngredient: "Atrazine, Pyroxasulfone, Fluthiacet-methyl", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "352-623", name: "Cinch Atz Lite", manufacturer: "Corteva Agriscience, LLC", activeIngredient: "Atrazine, S-Metolachlor", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "352-624", name: "Cinch Atz", manufacturer: "Corteva Agriscience, LLC", activeIngredient: "S-Metolachlor, Atrazine", family: "herbicide_corn_soy" },
  { epaRegistrationNumber: "352-779", name: "Prequel", manufacturer: "Corteva Agriscience, LLC", activeIngredient: "Isoxaflutole, Rimsulfuron", family: "herbicide_corn_soy" },

  // ── Rangeland / pasture herbicide (20) ─────────────────────────────────
  { epaRegistrationNumber: "228-530", name: "Manpower Herbicide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "2, 4-D, triisopropanolamine salt, Picloram, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "228-535", name: "Trooper 22k Herbicide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Picloram, potassium salt", family: "herbicide_range" },
  { epaRegistrationNumber: "228-586", name: "Trooper Extra Selective Herbicide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Dicamba, 2, 4-D, triisopropanolamine salt, Picloram, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "228-599", name: "Trooper Pro Herbicide", manufacturer: "Nufarm Americas, Inc.", activeIngredient: "Fluroxypyr 1-methylheptyl ester, Picloram, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "48273-15", name: "Toram 101", manufacturer: "Marman USA Inc.", activeIngredient: "Picloram, triisopropanolamine salt, 2, 4-D, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "53883-255", name: "Picloram 10.2 Herbicide", manufacturer: "Control Solutions, Inc.", activeIngredient: "Picloram, triisopropanolamine salt, 2, 4-D, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-17", name: "Tordon K", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, potassium salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-181", name: "Grazon Pc", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, potassium salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-182", name: "Grazon P+d", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, triisopropanolamine salt, 2, 4-D, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-480", name: "Surmount", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, triisopropanolamine salt, Fluroxypyr 1- methylheptyl ester", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-5", name: "Tordon 101 Mixture", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, triisopropanolamine salt, 2, 4-D, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-528", name: "GF-1249", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, potassium salt, Triclopyr, triethylamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-571", name: "Grazon Pd2", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Dicamba, 2, 4-D, triisopropanolamine salt, Picloram, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-6", name: "Tordon 22k Specialty Herbicid", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, potassium salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-653", name: "Grazon HL", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Picloram, 2, 4-D, choline salt", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-655", name: "Graslan L", manufacturer: "Corteva Agriscience LLC", activeIngredient: "2, 4-D, choline salt, Picloram", family: "herbicide_range" },
  { epaRegistrationNumber: "62719-717", name: "Mezavue", manufacturer: "Corteva Agriscience LLC", activeIngredient: "Aminopyralid, potassium salt, Picloram, potassium salt, Fluroxypyr 1-methylheptyl ester", family: "herbicide_range" },
  { epaRegistrationNumber: "81927-16", name: "Alligare Picloram+d", manufacturer: "Alligare, LLC", activeIngredient: "2, 4-D, triisopropanolamine salt, Picloram, triisopropanolamine salt", family: "herbicide_range" },
  { epaRegistrationNumber: "81927-18", name: "Alligare Picloram 22k", manufacturer: "Alligare, LLC", activeIngredient: "Picloram, potassium salt", family: "herbicide_range" },
  { epaRegistrationNumber: "81927-64", name: "Alligare Picloram + Fluroxypyr", manufacturer: "Alligare, LLC", activeIngredient: "Fluroxypyr 1-methylheptyl ester, Picloram", family: "herbicide_range" },

  // ── Glufosinate herbicide (2) ─────────────────────────────────
  { epaRegistrationNumber: "45002-33", name: "GP CON", manufacturer: "Albaugh, LLC.", activeIngredient: "Pelargonic acid, ammonium salt, Glufosinate", family: "herbicide_glufosinate" },
  { epaRegistrationNumber: "53883-468", name: "CSI 19-313B Glufosinate 11.33%", manufacturer: "Control Solutions, Inc.", activeIngredient: "Glufosinate", family: "herbicide_glufosinate" },

  // ── Rodenticide (indoor / structural) (20) ─────────────────────────────────
  { epaRegistrationNumber: "4-152", name: "Bonide Orchard Mouse Bait", manufacturer: "Bonide Products, LLC", activeIngredient: "Zinc phosphide (Zn3P2)", family: "rodenticide" },
  { epaRegistrationNumber: "814-9", name: "Force's Mous-Con No. 2", manufacturer: "Carajon Chemical Holdings, LLC", activeIngredient: "Zinc phosphide (Zn3P2)", family: "rodenticide" },
  { epaRegistrationNumber: "4271-10", name: "Pocket Gopher Bait Containin", manufacturer: "R & M Exterminators Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "4271-16", name: "Zinc Phosphide On Oats", manufacturer: "R & M Exterminators Inc.", activeIngredient: "Zinc phosphide (Zn3P2)", family: "rodenticide" },
  { epaRegistrationNumber: "4271-17", name: "Pocket Gopher Bait Containin", manufacturer: "R & M Exterminators Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "5042-34", name: "Rco Avalon Mixed Grain Goph", manufacturer: "Rco International Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "7173-113", name: "Rozol Tracking Powder", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-172", name: "Rozol Blue Tracking Powder", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-242", name: "Rozol Vole Bait", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-244", name: "Rozol Pocket Gopher Bait Ii", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-286", name: "Rozol Prairie Dog Bait", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-299", name: "Rozol Mini Blocks 0803", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-305", name: "Rozol Ground Squirrel Bait", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "7173-309", name: "Rozol Field Rodent Bait", manufacturer: "Liphatech, Inc.", activeIngredient: "Chlorophacinone", family: "rodenticide" },
  { epaRegistrationNumber: "10031-1", name: "Petersen's Pocket Gopher Kill", manufacturer: "Petersen Seeds Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "10031-2", name: "Petersen's Pocket Gopher Kill", manufacturer: "Petersen Seeds Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "10031-3", name: "Petersen's Pocket Gopher Kill", manufacturer: "Petersen Seeds Inc.", activeIngredient: "Strychnine", family: "rodenticide" },
  { epaRegistrationNumber: "12455-102", name: "Zp Rodent Oat Bait Ag", manufacturer: "Bell Laboratories, Inc.", activeIngredient: "Zinc phosphide (Zn3P2)", family: "rodenticide" },
  { epaRegistrationNumber: "12455-108", name: "Formus All-Weather Blox", manufacturer: "Bell Laboratories, Inc.", activeIngredient: "Brodifacoum", family: "rodenticide" },
  { epaRegistrationNumber: "12455-136", name: "PCQ Rodent Bait", manufacturer: "Bell Laboratories, Inc.", activeIngredient: "Diphacinone", family: "rodenticide" },

  // ── Soil / structural fumigant (20) ─────────────────────────────────
  { epaRegistrationNumber: "1015-74", name: "Ph3 Aluminum Phosphide Fumigant Pellets", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Aluminum phosphide", family: "fumigant" },
  { epaRegistrationNumber: "1015-75", name: "Ph3 Aluminum Phosphide Fumigant Bags", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Aluminum phosphide", family: "fumigant" },
  { epaRegistrationNumber: "1015-76", name: "Ph3 Aluminum Phosphide Fumigant Tablets", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Aluminum phosphide", family: "fumigant" },
  { epaRegistrationNumber: "1015-78", name: "Vikane", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Sulfuryl fluoride", family: "fumigant" },
  { epaRegistrationNumber: "1015-79", name: "Profume", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Sulfuryl fluoride", family: "fumigant" },
  { epaRegistrationNumber: "1015-80", name: "Master Fume", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Sulfuryl fluoride", family: "fumigant" },
  { epaRegistrationNumber: "1015-81", name: "Drexel Master Fume Ag", manufacturer: "Douglas Products And Packaging Company LLC", activeIngredient: "Sulfuryl fluoride", family: "fumigant" },
  { epaRegistrationNumber: "3008-121", name: "Timberfume Ii", manufacturer: "Koppers Performance Chemicals, Inc.", activeIngredient: "Chloropicrin", family: "fumigant" },
  { epaRegistrationNumber: "5481-423", name: "Metam 426", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-456", name: "Metam 376", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-458", name: "Metam 376", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-466", name: "Vapam Soil Fumigant Solutio", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-468", name: "Vapam Hl Soil Fumigant", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-474", name: "Sodcure 376", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-sodium", family: "fumigant" },
  { epaRegistrationNumber: "5481-483", name: "AMV 540", manufacturer: "Amvac Chemical Corporation", activeIngredient: "Metam-Potassium", family: "fumigant" },
  { epaRegistrationNumber: "5785-11", name: "Meth-O-Gas 100", manufacturer: "Lanxess Corporation", activeIngredient: "Methyl bromide (NO INERT USE)", family: "fumigant" },
  { epaRegistrationNumber: "5785-19", name: "Terr-O-Gas 70 Preplant Soil F", manufacturer: "Lanxess Corporation", activeIngredient: "Methyl bromide (NO INERT USE), Chloropicrin", family: "fumigant" },
  { epaRegistrationNumber: "5785-22", name: "Terr-O-Gas 98", manufacturer: "Lanxess Corporation", activeIngredient: "Methyl bromide (NO INERT USE)", family: "fumigant" },
  { epaRegistrationNumber: "5785-24", name: "Terr-O-Gas 67", manufacturer: "Lanxess Corporation", activeIngredient: "Methyl bromide (NO INERT USE), Chloropicrin", family: "fumigant" },
  { epaRegistrationNumber: "5785-28", name: "Terr-O-Gas 57 Preplant Soil F", manufacturer: "Lanxess Corporation", activeIngredient: "Methyl bromide (NO INERT USE), Chloropicrin", family: "fumigant" },

  // ── Restricted fungicide / nematicide (0) ─────────────────────────────────

  // ── Wood preservative (15) ─────────────────────────────────
  { epaRegistrationNumber: "363-14", name: "The C-4 Brand Black Creosote Coal Tar Solution", manufacturer: "Coopers Creek Chemical Corporation", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "363-15", name: "The C-4 Brand Coopersote Creosote Oil", manufacturer: "Coopers Creek Chemical Corporation", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "363-48", name: "THE C-4 BRAND: CREOSOTE/PETROLEUM", manufacturer: "Coopers Creek Chemical Corporation", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61468-1", name: "Coal Tar Creosote", manufacturer: "Koppers Inc.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61468-3", name: "Creosote Solution", manufacturer: "Koppers Inc.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61468-9", name: "Creosote/Petroleum Solutio", manufacturer: "Koppers Inc.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61470-1", name: "Coal Tar Creosote", manufacturer: "Rain Cii Carbon LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61470-3", name: "Coal Tar Creosote P2", manufacturer: "Rain Cii Carbon LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "61470-4", name: "P3 Creosote-Petroleum Solution", manufacturer: "Rain Cii Carbon LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "82024-1", name: "Creosote-Solution", manufacturer: "Lone Star Specialty Products, LLC.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "82024-2", name: "Creosote Oil", manufacturer: "Lone Star Specialty Products, LLC.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "82024-3", name: "Creosote Petroleum Solution", manufacturer: "Lone Star Specialty Products, LLC.", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "97080-6", name: "Creosote", manufacturer: "Arbor Preservative Systems, LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "97080-7", name: "Creosote Solution", manufacturer: "Arbor Preservative Systems, LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
  { epaRegistrationNumber: "97080-8", name: "Creosote For Pressure Treatment Application", manufacturer: "Arbor Preservative Systems, LLC", activeIngredient: "Coal tar creosote", family: "wood_preservative" },
];

// Stable id generator: rup-<epa-reg-with-dash-preserved-lowercased>. EPA reg
// numbers are unique by construction so the id stays stable across reseeds.
const idFor = (epa: string) => `rup-${epa.toLowerCase()}`;

export function buildRupProductSeed(timestamp: string): Product[] {
  return RUPS.map((r) => ({
    id: idFor(r.epaRegistrationNumber),
    catalogVersion: RUP_CATALOG_VERSION,
    name: r.name,
    epaRegistrationNumber: r.epaRegistrationNumber,
    rupStatus: "yes",
    createdAt: timestamp,
    activeIngredient: r.activeIngredient,
    manufacturer: r.manufacturer,
  }));
}

// Per-family lookup so seeded demo records can pick a thematically-coherent
// product (e.g. a rodenticide for an indoor record, a fumigant for a
// structural one, a herbicide for an outdoor field record).
export function rupIdsByFamily(family: RupFamily): string[] {
  return RUPS.filter((r) => r.family === family).map((r) =>
    idFor(r.epaRegistrationNumber)
  );
}
